name: natzzzz
description: Malwares & ctfs...
meta_description: "Malwares & ctfs..."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://github.com/natzzzz"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "natzzzz"

# Disqus config
disqus-shortname: ""
